package:
  name: R&S-Power-Supply
  version: "0.1.0"

source:
  path: ..

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install ."

requirements:
  host:
    - python
    - pip
    - setuptools

  run:
    - python
    - pyvisa

about:
  summary: VISA power supply controller for R&S NGE100